### ISSUE TITLE
`Dockerfile.devel-gpu` is broken

### ISSUE THREAD

**Issue by fdoumet** [tensorflow/serving#1338]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian GNU/Linux 9 (stretch)
- **TensorFlow Serving installed from (source or binary)**: source
- **TensorFlow Serving version**: HEAD from master branch

### Describe the problem
`Dockerfile.devel-gpu` seems to be broken. When running `docker build -f ./Dockerfile.devel-gpu .`, it errors out with the following:

```
ERROR: /tensorflow-serving/tensorflow_serving/model_servers/BUILD:348:1: error loading package '@org_tensorflow//tensorflow/core/platform/s3': in /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/org_tensorflow/tensorflow/tensorflow.bzl: Encountered error while reading extension file 'build_defs.bzl': no such package '@local_config_tensorrt//': Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/org_tensorflow/third_party/tensorrt/tensorrt_configure.bzl", line 67
		find_cuda_config(repository_ctx, ["tensorrt"])
	File "/root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 666, in find_cuda_config
		auto_configure_fail(("Failed to run find_cuda_config...))
	File "/root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 274, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Failed to run find_cuda_config.py: Could not find any NvInfer.h matching version '5.0.2' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        '/usr/lib/x86_64-linux-gnu'

 and referenced by '//tensorflow_serving/model_servers:tensorflow_model_server_main_lib'
ERROR: Analysis of target '//tensorflow_serving/model_servers:tensorflow_model_server' failed; build aborted: error loading package '@org_tensorflow//tensorflow/core/platform/s3': in /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/org_tensorflow/tensorflow/tensorflow.bzl: Encountered error while reading extension file 'build_defs.bzl': no such package '@local_config_tensorrt//': Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/org_tensorflow/third_party/tensorrt/tensorrt_configure.bzl", line 67
		find_cuda_config(repository_ctx, ["tensorrt"])
	File "/root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 666, in find_cuda_config
		auto_configure_fail(("Failed to run find_cuda_config...))
	File "/root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 274, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Failed to run find_cuda_config.py: Could not find any NvInfer.h matching version '5.0.2' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        '/usr/lib/x86_64-linux-gnu'

INFO: Elapsed time: 35.124s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (11 packages loaded, 64 targets co\
nfigured)
    currently loading: @org_tensorflow//tensorflow/core/platform/s3
The command '/bin/sh -c ln -s /usr/local/cuda/lib64/stubs/libcuda.so /usr/local/cuda/lib64/stubs/libcuda.so.1 &&     LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:${LD_LIBRARY_PATH}     bazel build --color=yes --curses=yes --config=cuda --copt="-fPIC"    ${TF_SERVING_BAZEL_OPTIONS}     --verbose_failures     --output_filter=DONT_MATCH_ANYTHING     ${TF_SERVING_BUILD_OPTIONS}     tensorflow_serving/model_servers:tensorflow_model_server &&     cp bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server     /usr/local/bin/ &&     rm /usr/local/cuda/lib64/stubs/libcuda.so.1' returned a non-zero code: 1
```

### Exact Steps to Reproduce
1. Run `git clone https://github.com/tensorflow/serving.git`
2. Run  `docker build -f ./tensorflow_serving/tools/docker/Dockerfile.devel-gpu .`

**Comment by gowtham-kp** [comment]
@fdoumet Can you please prove us with the following information:
CUDA Version:
Driver Version:
TF Serving Version:
CUDA Compute Capability:

Thanks

**Comment by fdoumet** [comment]
@gowtham-kp, just using the defaults from the `Dockerfile.devel-gpu` file. Not making any changes.

**Comment by mpjlu** [comment]
I have the save issue.

**Comment by aaroey** [comment]
@fdoumet I think this is fixed, would you please try again? Thanks.

**Comment by fdoumet** [comment]
@aaroey, same error is still happening. I had tried pulling tf from head too before filing this issue, with no success.

**Comment by aaroey** [comment]
@fdoumet I tried but I cannot reproduce the problem. How did you pull tf from head? Also, would you please make sure you had clean up the docker build cache before you run `docker build`?

Thanks.

**Comment by fdoumet** [comment]
@aaroey I was pulling the latest by updating the `WORKSPACE` file as you did. Running `docker build` with `--no-cache` did get me past my initial error though! Now I'm getting another error:

```
ERROR: /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/org_tensorflow/tensorflow/stream_executor/cuda/BUILD:285:1: C++ compilation of rule '@org_tensorflow//tensorflow/stream_executor/cuda:cudnn_plugin' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/execroot/tf_serving && \
  exec env - \
    LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64 \
    PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/stream_executor/cuda/_objs/cudnn_plugin/cuda_dnn.d '-frandom-seed=bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/stream_executor/cuda/_objs/cudnn_plugin/cuda_dnn.o' -D__CLANG_SUPPORT_DYN_ANNOTATION__ -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' '-DEIGEN_HAS_TYPE_TRAITS=0' -DTF_USE_SNAPPY -iquote external/org_tensorflow -iquote bazel-out/k8-opt/genfiles/external/org_tensorflow -iquote bazel-out/k8-opt/bin/external/org_tensorflow -iquote external/com_google_absl -iquote bazel-out/k8-opt/genfiles/external/com_google_absl -iquote bazel-out/k8-opt/bin/external/com_google_absl -iquote external/nsync -iquote bazel-out/k8-opt/genfiles/external/nsync -iquote bazel-out/k8-opt/bin/external/nsync -iquote external/eigen_archive -iquote bazel-out/k8-opt/genfiles/external/eigen_archive -iquote bazel-out/k8-opt/bin/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/k8-opt/genfiles/external/local_config_sycl -iquote bazel-out/k8-opt/bin/external/local_config_sycl -iquote external/gif_archive -iquote bazel-out/k8-opt/genfiles/external/gif_archive -iquote bazel-out/k8-opt/bin/external/gif_archive -iquote external/jpeg -iquote bazel-out/k8-opt/genfiles/external/jpeg -iquote bazel-out/k8-opt/bin/external/jpeg -iquote external/protobuf_archive -iquote bazel-out/k8-opt/genfiles/external/protobuf_archive -iquote bazel-out/k8-opt/bin/external/protobuf_archive -iquote external/zlib_archive -iquote bazel-out/k8-opt/genfiles/external/zlib_archive -iquote bazel-out/k8-opt/bin/external/zlib_archive -iquote external/com_googlesource_code_re2 -iquote bazel-out/k8-opt/genfiles/external/com_googlesource_code_re2 -iquote bazel-out/k8-opt/bin/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/k8-opt/genfiles/external/farmhash_archive -iquote bazel-out/k8-opt/bin/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/k8-opt/genfiles/external/fft2d -iquote bazel-out/k8-opt/bin/external/fft2d -iquote external/highwayhash -iquote bazel-out/k8-opt/genfiles/external/highwayhash -iquote bazel-out/k8-opt/bin/external/highwayhash -iquote external/double_conversion -iquote bazel-out/k8-opt/genfiles/external/double_conversion -iquote bazel-out/k8-opt/bin/external/double_conversion -iquote external/snappy -iquote bazel-out/k8-opt/genfiles/external/snappy -iquote bazel-out/k8-opt/bin/external/snappy -iquote external/hwloc -iquote bazel-out/k8-opt/genfiles/external/hwloc -iquote bazel-out/k8-opt/bin/external/hwloc -iquote external/local_config_cuda -iquote bazel-out/k8-opt/genfiles/external/local_config_cuda -iquote bazel-out/k8-opt/bin/external/local_config_cuda -Ibazel-out/k8-opt/bin/external/local_config_cuda/cuda/_virtual_includes/cuda_virtual_headers -isystem external/nsync/public -isystem bazel-out/k8-opt/genfiles/external/nsync/public -isystem bazel-out/k8-opt/bin/external/nsync/public -isystem external/eigen_archive -isystem bazel-out/k8-opt/genfiles/external/eigen_archive -isystem bazel-out/k8-opt/bin/external/eigen_archive -isystem external/gif_archive/lib -isystem bazel-out/k8-opt/genfiles/external/gif_archive/lib -isystem bazel-out/k8-opt/bin/external/gif_archive/lib -isystem external/protobuf_archive/src -isystem bazel-out/k8-opt/genfiles/external/protobuf_archive/src -isystem bazel-out/k8-opt/bin/external/protobuf_archive/src -isystem external/zlib_archive -isystem bazel-out/k8-opt/genfiles/external/zlib_archive -isystem bazel-out/k8-opt/bin/external/zlib_archive -isystem external/farmhash_archive/src -isystem bazel-out/k8-opt/genfiles/external/farmhash_archive/src -isystem bazel-out/k8-opt/bin/external/farmhash_archive/src -isystem external/double_conversion -isystem bazel-out/k8-opt/genfiles/external/double_conversion -isystem bazel-out/k8-opt/bin/external/double_conversion -isystem external/hwloc/hwloc -isystem bazel-out/k8-opt/genfiles/external/hwloc/hwloc -isystem bazel-out/k8-opt/bin/external/hwloc/hwloc -isystem external/hwloc/include -isystem bazel-out/k8-opt/genfiles/external/hwloc/include -isystem bazel-out/k8-opt/bin/external/hwloc/include -isystem external/local_config_cuda/cuda/cuda/include -isystem bazel-out/k8-opt/genfiles/external/local_config_cuda/cuda/cuda/include -isystem bazel-out/k8-opt/bin/external/local_config_cuda/cuda/cuda/include '-std=c++11' -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fPIE -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -fno-omit-frame-pointer -no-canonical-prefixes -fno-canonical-system-headers -DNDEBUG -g0 -O2 -ffunction-sections -fdata-sections -fPIC '-march=native' -O3 '-D_GLIBCXX_USE_CXX11_ABI=0' -c external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc -o bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/stream_executor/cuda/_objs/cudnn_plugin/cuda_dnn.o)
Execution platform: @bazel_tools//platforms:host_platform
external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc:46:42: fatal error: third_party/gpus/cudnn/cudnn.h: No such file or directory
compilation terminated.
Target //tensorflow_serving/model_servers:tensorflow_model_server failed to build
INFO: Elapsed time: 4985.021s, Critical Path: 120.30s
INFO: 3050 processes: 3050 local.
FAILED: Build did NOT complete successfully
The command '/bin/sh -c ln -s /usr/local/cuda/lib64/stubs/libcuda.so /usr/local/cuda/lib64/stubs/libcuda.so.1 &&     LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:${LD_LIBRARY_PATH}     bazel build --color=yes --curses=yes --config=cuda --copt="-fPIC"    ${TF_SERVING_BAZEL_OPTIONS}     --verbose_failures     --output_filter=DONT_MATCH_ANYTHING     ${TF_SERVING_BUILD_OPTIONS}     tensorflow_serving/model_servers:tensorflow_model_server &&     cp bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server     /usr/local/bin/ &&     rm /usr/local/cuda/lib64/stubs/libcuda.so.1' returned a non-zero code: 1
```
Any ideas?

**Comment by aaroey** [comment]
@fdoumet for that I don't know, maybe there is another bug from TF head. But the latest nightly GPU docker image was updated successfully (https://hub.docker.com/r/tensorflow/serving/tags/), so would you please try to rollback the WORKSPACE change but use head of TF Serving repository to build?

**Comment by fdoumet** [comment]
Yup, build correctly now. Thanks for the help! Closing the issue as resolved.
