### ISSUE TITLE
Expired GPG Key for Ubuntu binary

### ISSUE THREAD

**Issue by SirOibaf** [tensorflow/serving#1395]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow Serving installed from (source or binary)**: apt
- **TensorFlow Serving version**: 1.14.0

### Describe the problem
I'm trying to install `tensorflow-model-server` 1.14.0 through APT but it seems that the GPG key used to sign the package is expired.

```
W: GPG error: http://storage.googleapis.com/tensorflow-serving-apt testing InRelease: The following signatures were invalid: KEYEXPIRED 1562881134  KEYEXPIRED 1562881134  KEYEXPIRED 1562881134
```

### Exact Steps to Reproduce
See documentation: https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/setup.md#installing-using-apt

**Comment by golisandeep3** [comment]
I am facing the same issue.

**Comment by orf** [comment]
```
$ gpg tensorflow-serving.release.pub.gpg                                                 
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa4096 2017-07-13 [SC] [expired: 2019-07-11]
      916E2B2FEBC274930BACA9D9544B7F63BF9E4D5F
uid           Tensorflow Serving Developer (Tensorflow Serving APT repository key) <tensorflow-serving-dev@googlegroups.com>
sub   rsa4096 2017-07-13 [E] [expired: 2019-07-11]
```

Expired two days ago.

**Comment by BalajiB197** [comment]
I am facing same issue, when i try to do apt update I face error.
[ expired] Tensorflow Serving Developer (Tensorflow Serving APT repository key) <tensorflow-serving-dev@googlegroups.com>

**Comment by TianrenWang** [comment]
Same problem here. Today of all days I am using Sagemaker LOL.

**Comment by gauravgola96** [comment]
I am facing same problem today.
`An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://storage.googleapis.com/tensorflow-serving-apt stable InRelease: The following signatures were invalid: EXPKEYSIG 544B7F63BF9E4D5F Tensorflow Serving Developer (Tensorflow Serving APT repository key`

**Comment by naveenkumarmulabitmovin** [comment]
I am also facing the same problem when I update apt 
The following signatures were invalid: EXPKEYSIG 544B7F63BF9E4D5F Tensorflow Serving Developer (Tensorflow Serving APT repository key) <tensorflow-serving-dev@googlegroups.com>
Fetched 91.7 kB in 1s (62.3 kB/s)
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://storage.googleapis.com/tensorflow-serving-apt stable InRelease: The following signatures were invalid: EXPKEYSIG 544B7F63BF9E4D5F Tensorflow Serving Developer (Tensorflow Serving APT repository key) <tensorflow-serving-dev@googlegroups.com>
W: Failed to fetch http://storage.googleapis.com/tensorflow-serving-apt/dists/stable/InRelease  The following signatures were invalid: EXPKEYSIG 544B7F63BF9E4D5F Tensorflow Serving Developer (Tensorflow Serving APT repository key) <tensorflow-serving-dev@googlegroups.com>
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by radiodee1** [comment]
I'm having this problem too. expired.

**Comment by TianrenWang** [comment]
I don't know if this applies to your situations, but I was using AWS SageMaker and adding `--allow-unauthenticated` after `RUN apt-get update && apt-get install tensorflow-model-server` solved the problem for me. But you will expose yourself to security risks, so be warned.

**Comment by saeedaghabozorgi** [comment]
I have same problem too.

**Comment by minglotus-6** [comment]
We are working on the issue internally. Conservatively it should take one day to fix.

**Comment by minglotus-6** [comment]
This should work now.

**Comment by BalajiB197** [comment]
@minglotus-6 
How to resolve it. I am facing issue still when I execute sudo apt update.
The following signatures were invalid: EXPKEYSIG 544B7F63BF9E4D5F Tensorflow Serving Developer (Tensorflow Serving APT repository key) <tensorflow-serving-dev@googlegroups.com

**Comment by minglotus-6** [comment]
I'm able to use apt-get to install TFS in an isolated docker environment before closing this issue.

Re Balaji, if you are still facing the issue, could you provide full commands and error messages?

**Comment by David-Parker** [comment]
I am getting this issue currently when I run sudo apt-get update on Ubunutu Server 16.04 LTS in an Azure VM:

Ign:11 http://storage.googleapis.com/tensorflow-serving-apt stable InRelease
Fetched 3,012 B in 1s (2,348 B/s)
Reading package lists... Done
W: GPG error: http://storage.googleapis.com/tensorflow-serving-apt stable InRelease: The following signatures were invalid: KEYEXPIRED 1562881134  KEYEXPIRED 1562881134  KEYEXPIRED 1562881134

**Comment by David-Parker** [comment]
I am able to get the new key with the following command:

curl https://storage.googleapis.com/tensorflow-serving-apt/tensorflow-serving.release.pub.gpg | sudo apt-key add -

**Comment by minglotus-6** [comment]
Sorry for the confusion, Please following the installation instructions (https://www.tensorflow.org/tfx/serving/setup#installation_2) to install TFS server.

The instructions specifies to import the keys.

**Comment by BalajiB197** [comment]
@minglotus-6  I was able to resolve this after following the instructions for installing tensorflow-model-server.
The confusion was how we got this error, here the thing we have installed tensorflow earlier, but in the recent release, there is an update key for model-serving.
Anyways thanks.

**Comment by thijstriemstra** [comment]
Key expired again.... Opened #1896
