### ISSUE TITLE
'module' object has no attribute 'app' in Basic TensorFlow Serving tutorial.

### ISSUE THREAD

**Issue by ericmclachlan** [tensorflow/serving#1534]
Executing the 3 command-sets of this Basic TensorFlow Serving tutorial should not result in errors. This is supposed to be the carrot for introducing folk to TensorFlow Servings.

https://www.tensorflow.org/tfx/serving/serving_basic

# Problem

The following error is reported when trying to test the server.

```
AttributeError: 'module' object has no attribute 'app'
```

# Steps to reproduce:

## Step 1

```sh
git clone https://github.com/tensorflow/serving.git
cd serving
rm -rf /tmp/mnist
tools/run_in_docker.sh python tensorflow_serving/example/mnist_saved_model.py \
  /tmp/mnist
```
The export was successful.

## Step 2

```sh
docker run -p 8500:8500 \
--mount type=bind,source=/tmp/mnist,target=/models/mnist \
-e MODEL_NAME=mnist -t tensorflow/serving &
```
Seems to correctly start the serving.

Output:
```
2020-01-17 11:50:13.844715: I tensorflow_serving/model_servers/server.cc:86] Building single TensorFlow model file config:  model_name: mnist model_base_path: /models/mnist
2020-01-17 11:50:13.845026: I tensorflow_serving/model_servers/server_core.cc:462] Adding/updating models.
2020-01-17 11:50:13.845064: I tensorflow_serving/model_servers/server_core.cc:573]  (Re-)adding model: mnist
2020-01-17 11:50:13.945571: I tensorflow_serving/core/basic_manager.cc:739] Successfully reserved resources to load servable {name: mnist version: 1}
2020-01-17 11:50:13.945629: I tensorflow_serving/core/loader_harness.cc:66] Approving load for servable version {name: mnist version: 1}
2020-01-17 11:50:13.945669: I tensorflow_serving/core/loader_harness.cc:74] Loading servable version {name: mnist version: 1}
2020-01-17 11:50:13.945725: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:31] Reading SavedModel from: /models/mnist/1
2020-01-17 11:50:13.947023: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:54] Reading meta graph with tags { serve }
2020-01-17 11:50:13.947109: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:264] Reading SavedModel debug info (if present) from: /models/mnist/1
2020-01-17 11:50:13.947258: I external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-01-17 11:50:13.964276: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:203] Restoring SavedModel bundle.
2020-01-17 11:50:13.970068: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:152] Running initialization op on SavedModel bundle at path: /models/mnist/1
2020-01-17 11:50:13.973488: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:333] SavedModel load for tags { serve }; Status: success: OK. Took 27760 microseconds.
2020-01-17 11:50:13.973799: I tensorflow_serving/servables/tensorflow/saved_model_warmup.cc:105] No warmup data file found at /models/mnist/1/assets.extra/tf_serving_warmup_requests
2020-01-17 11:50:13.974119: I tensorflow_serving/core/loader_harness.cc:87] Successfully loaded servable version {name: mnist version: 1}
2020-01-17 11:50:13.978468: I tensorflow_serving/model_servers/server.cc:358] Running gRPC ModelServer at 0.0.0.0:8500 ...
[warn] getaddrinfo: address family for nodename not supported
[evhttp_server.cc : 238] NET_LOG: Entering the event loop ...
2020-01-17 11:50:13.980440: I tensorflow_serving/model_servers/server.cc:378] Exporting HTTP/REST API at:localhost:8501 ...
```

## Step 3

```sh
tools/run_in_docker.sh python tensorflow_serving/example/mnist_client.py \
  --num_tests=1000 --server=127.0.0.1:8500
```
Here I was presented with an error message.

```
tools/run_in_docker.sh python tensorflow_serving/example/mnist_client.py \
>   --num_tests=1000 --server=127.0.0.1:8500
== Pulling docker image: tensorflow/serving:nightly-devel
nightly-devel: Pulling from tensorflow/serving
Digest: sha256:5af52f318944078fbbe6e8dd607d830912e42b5666d7582a3c65b35ff22e85ec
Status: Image is up to date for tensorflow/serving:nightly-devel
docker.io/tensorflow/serving:nightly-devel
== Running cmd: sh -c 'cd /mnt/c/Echosec/serving; python tensorflow_serving/example/mnist_client.py --num_tests=1000 --server=127.0.0.1:8500'
2020-01-17 11:51:01.926219: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-01-17 11:51:01.926358: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-01-17 11:51:01.926393: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "tensorflow_serving/example/mnist_client.py", line 44, in <module>
    tf.app.flags.DEFINE_integer('concurrency', 1,
AttributeError: 'module' object has no attribute 'app'
```

### Additional context:

Seems to be related to: 
https://github.com/tensorflow/serving/issues/1468

### System information
- **OS Platform and Distribution**: Ubuntu 18.04 on WSL
- **TensorFlow Serving installed from**: docker image: tensorflow/serving:nightly-devel
- **TensorFlow Serving version**: docker image: tensorflow/serving:nightly-devel

Nightly, in this case, is probably 2020-01-16/17

**Comment by upwindflys** [comment]
I fixed this by change code 'tf.app' to code'tf.compat.v1.app' ,it works but get 'Inference error rate: 100.0%' , at the same time ,'training accuracy 0.9092',I'm confused, does serving works right?

**Comment by gowthamkpr** [comment]
As mentioned [here](https://github.com/tensorflow/serving/issues/1468#issuecomment-567607649) this should be fixed now. What version of Tensorflow serving are you using. Can you please use the latest version of tensorflow serving and let me know if the issue still persists. Thanks!

**Comment by gowthamkpr** [comment]
@ericmclachlan @upwindflys Sorry for the above comment. This has been committed in couple of days ago as shown [here](https://github.com/tensorflow/serving/blob/e085cb37b4b5c62154aa063dcbb781b24d5b3fd4/tensorflow_serving/example/mnist_client.py#L44)

Please wait for a few more days until we release an other docker image where the change will be committed.

**Comment by ericmclachlan** [comment]
Thank you, @gowthamkpr. I'm glad the team found a solution.

**Comment by gowthamkpr** [comment]
Closing this issue as it has been resolved.

**Comment by barrierye** [comment]
Now the problem is still there. And I found this https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/mnist_client.py#L50
