### ISSUE TITLE
Export server metrics

### ISSUE THREAD

**Issue by FNegrello** [tensorflow/serving#462]
Hello,
Is there any way to have metrics (response time, prediction time, number of requests...) on the server ?
Thank you.

**Comment by chrisolston** [comment]
Currently we don't have any built-in solution for that. Contributions welcome :)

Perhaps a good way to structure it would be to subclass ServableStateMonitor with something that also maintains & exports statistics.

**Comment by ynqa** [comment]
How is this issue (or similar issue: #711) going?

**Comment by ynqa** [comment]
@FNegrello @chrisolston 
How is this issue (or similar issue: #711) going?

**Comment by ynqa** [comment]
If nobody push commits here now, I'd like to contribute.

Then, I also ask you the metrics definitions:
1. What are the elements output? (e.g. model_name, model_version, and elapsed_time per prediction...)
1. Metrics format (e.g. json, csv...)
1. How does it output the metrics?
    - @FNegrello case: Output metrics per calling `Predict` service, and use `LOG` (for stdout) or syslog in [this](https://github.com/Cdiscount/serving/commit/cfaae42556a81f8a2bbf98916e77b48332a25421) commit.
    - Another suggestion: Add the service for metrics to pull them from the monitoring systems.

**Comment by cfregly** [comment]
the Prometheus metrics format - and pull model - is a good place to start.

works well with kubernetes, has c++ bindings, has a strong community, solid (turing-complete) query language, and great integration with a newly-updated Grafana UI.

for now, i would start with the following:

model_name

model_version

any custom labels/tags the user passes in

request counts

error counts (for each type of error you see in the TF Serving code)

graph execution time (aka prediction time)

in the future, i’d like to see the following:

custom ops for timing specific parts of the graph (similar in concept to the batch/unbatch ops, except start_timer/end_timer)

individual request tracing like ZipKin or Jaeger

model ensemble statistics (which models were involved in the final prediction)

a/b test metrics

**Comment by ynqa** [comment]
> the Prometheus metrics format - and pull model - is a good place to start.

Sure. In this case, which is the better?
1. Add the service [here]
(https://github.com/tensorflow/serving/blob/master/tensorflow_serving/apis/prediction_service.proto) for output metrics. but I'm not sure to pull metrics from gRPC service directly...
1. Preparing endpoint (e.g. `/metrics`) for HTTP requests, such as: https://github.com/grpc-ecosystem/go-grpc-prometheus

**Comment by ynqa** [comment]
> the Prometheus metrics format - and pull model - is a good place to start.

@cfregly Sure. In this case, which is the better on using Prometheus?
1. Add the service [here](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/apis/prediction_service.proto) for output metrics. but I'm not sure to pull metrics from gRPC service directly...
1. Preparing endpoint (e.g. `/metrics`) for HTTP requests, such as: https://github.com/grpc-ecosystem/go-grpc-prometheus

**Comment by ynqa** [comment]
@cfregly I just also implemented tensorflow serving exporter for prometeus besides server metrics, here: https://github.com/ynqa/tf_serving_exporter. It still a metric of model state only.

**Comment by ynqa** [comment]
I just also implemented tensorflow serving exporter for prometeus besides server metrics, here: https://github.com/ynqa/tf_serving_exporter. It still a metric of model state only.

**Comment by thomasjungblut** [comment]
I would love to see prometheus support here as well, any traction from the PR #800? I can see it got a little stale.

**Comment by ynqa** [comment]
@thomasjungblut It's okay to move the repo into here. It's related to that PR, which is not merged. So the exporter handles only model status as a metric got by `GetModelStatus` now.

**Comment by jlewi** [comment]
@cfregly @ynqa is #800 compatible with prometheus?

**Comment by ynqa** [comment]
@jlewi I also implemented prometheus exporter from tensorflow serving:   https://github.com/ynqa/tf_serving_exporter
But now, the exporter handles only model status as a metric got by `GetModelStatus`. If #800 is merged, I'll add a component to export model metrics using its service.

**Comment by ynqa** [comment]
@jlewi The exporter is necessary between prometheus and tensorflow serving.

**Comment by ynqa** [comment]
@jlewi Yes.

**Comment by ynqa** [comment]
@jlewi Yes. The exporter is needed between prometheus and tf serving.

**Comment by wydwww** [comment]
Hi @chrisolston 
Any update from tf-serving team since your comment in https://github.com/tensorflow/serving/pull/800#issuecomment-414407903?

**Comment by ynqa** [comment]
@wydwww Updates about prometheus exporter are described on this release note: https://github.com/tensorflow/serving/blob/master/RELEASE.md#major-features-and-improvements

**Comment by wydwww** [comment]
@ynqa Thanks for your reply! I checked this commit and set up the monitoring. I can see the following types of metrics by simply curl or in Prometheus:
```
# TYPE :tensorflow:cc:saved_model:load_attempt_count counter
# TYPE :tensorflow:cc:saved_model:load_latency counter
# TYPE :tensorflow:contrib:session_bundle:load_attempt_count counter
# TYPE :tensorflow:contrib:session_bundle:load_latency counter
# TYPE :tensorflow:core:direct_session_runs counter
# TYPE :tensorflow:serving:request_example_count_total counter
# TYPE :tensorflow:serving:request_example_counts histogram
# TYPE :tensorflow:serving:request_log_count counter
```
Is there a way to get the metrics for prediction time of a request and the time when model_server received a request? I am trying to test in the lifecycle of one prediction request, how much time is spent on the network and how much on prediction by model_server.

**Comment by ynqa** [comment]
@wydwww welcome. Now, I think there are some ways to collect your own custom metrics:
1. estimate and export the metrics on your client side
2. fork tf serving and add exporting mechanism into that

**Comment by wydwww** [comment]
@ynqa Thanks. 
Currently I use a program running on server to receive requests from client and send them to model server. This can remove time spent on internet.

**Comment by litaxc** [comment]
I saw there was 021efbd3281aa815cab0b35eab6d6d25249c12d4, which expose prometheus metrics on `/monitoring/prometheus/metrics`.

However, I tested the tensorflow/serving docker image with tag nightly/latest/1.12.0, but all received 404 not found on `/monitoring/prometheus/metrics`. While `/v1/models/model` worked without problem.

Reproduce with:
```docker run --rm -it -v `pwd`/models:/models -p 8501:8501 tensorflow/serving:1.12.0```

**Comment by netfs** [comment]
@litaxc i think your issue is same as #1180 -- this is fixed in latest 1.13.0-rc1 release. can you please help test the published docker image? -- thanks!

**Comment by litaxc** [comment]
@netfs I tried 1.13.0-rc1 but still got 404 Not Found on `/monitoring/prometheus/metrics`
I use the exported model from https://www.tensorflow.org/serving/serving_basic and still cannot get any prometheus metrics.

**Comment by netfs** [comment]
you need to pass `--monitoring_config_file=<file>` to the model server to enable prometheus endpoint. the file format looks like [this](https://github.com/tensorflow/serving/blob/e92e8313b433472e1d0699e7e2606da383b706bb/tensorflow_serving/servables/tensorflow/testdata/monitoring_config.txt#L1) (you can skip `path` if you want to use the default). see the [unit test](https://github.com/tensorflow/serving/blob/e92e8313b433472e1d0699e7e2606da383b706bb/tensorflow_serving/model_servers/tensorflow_model_server_test.py#L177) for more details.

**Comment by litaxc** [comment]
@netfs it works! thank you!

**Comment by ynqa** [comment]
> you need to pass --monitoring_config_file=<file> to the model server to enable prometheus endpoint.

@netfs Is documentation about monitoring progressing? Or could I write?

**Comment by unclepeddy** [comment]
@ynqa Idt anyone is actively working on monitoring docs so please feel free to write one up.

**Comment by zaktab** [comment]
Is there documentation about how to access the `/monitoring/prometheus/metrics` endpoint?

**Comment by netfs** [comment]
> Is there documentation about how to access the `/monitoring/prometheus/metrics` endpoint?

#1348 is attempting to document monitoring. feel free to comment on that PR if you want to see additional information added.

**Comment by blester125** [comment]
Are there any plan to add a metric that is like prediction time that has `model_path` as a label so we can see things like the average latency of a request for a given model?

**Comment by Davidbcn23** [comment]
Hi @ynqa  i'm working in a python client based in your code to get serving metrics and i'm having some difficulties to make it works. My code looks like:
   
    import grpc     
    import tensorflow as tf

    from tensorflow_serving.apis import get_model_metrics_pb2
    from tensorflow_serving.apis import model_service_pb2_grpc


    def main():
        channel = grpc.insecure_channel("127.0.0.1:8501")
        stub = model_service_pb2_grpc.ModelServiceStub(channel)
        request = get_model_metrics_pb2.GetModelMetricsRequest()
        request.model_spec.name = '1'
        request.model_spec.signature_name = 'get_model_metrics'
        response = stub.GetModelMetrics(request, 100)

    if response.status.error_code == 0:
        print("Success")
        print(response)
    else:
        print("Fail!")
        print(response.status.error_code)
        print(response.status.error_message)


    if __name__ == '__main__':
        tf.app.run()

And when I try to tun it this message appears:

        from tensorflow_serving.apis import get_model_metrics_pb2
    ImportError: cannot import name 'get_model_metrics_pb2' from 'tensorflow_serving.apis'

I generate get_model_metrics.pb2 with protoc so i assume the error is not here. Searching it on Google and reading what people says, i'm sure that is a circular depedence failure but i don't know how to fix it properly. Maybe you have any idea or know someone who is working on it. Thanks a lot!

**Comment by PayneJoe** [comment]
> @ynqa Thanks.
> Currently I use a program running on server to receive requests from client and send them to model server. This can remove time spent on internet.

Hi, Since these metrics

> # TYPE :tensorflow:serving:request_example_count_total counter
> # TYPE :tensorflow:serving:request_example_counts histogram
> # TYPE :tensorflow:serving:request_log_count counter

NOT supported by the official version yet, what is the cheapest way to get these metrics? Any improvement yet?

By the way, number of requests received per second and time cost per request are what I want.

**Comment by PayneJoe** [comment]
> Currently we don't have any built-in solution for that. Contributions welcome :)
> 
> Perhaps a good way to structure it would be to subclass ServableStateMonitor with something that also maintains & exports statistics.

`# TYPE :tensorflow:data:autotune counter
# TYPE :tensorflow:data:bytes_read counter
# TYPE :tensorflow:data:elements counter
# TYPE :tensorflow:data:optimization counter
# TYPE :tensorflow:serving:model_warmup_latency histogram
# TYPE :tensorflow:serving:request_example_count_total counter
# TYPE :tensorflow:serving:request_example_counts histogram
# TYPE :tensorflow:serving:request_log_count counter`

Hi, chrisolston, I'm wondering why these metrics are empty by now?  They are the TODO list?

Thanks,

**Comment by abhinavos7a** [comment]
I am running tf serving as docker container and exposed a REST endpoint with prometheus metrics enabled.

I could see following stats from prometheus endpoint 
`
# TYPE :tensorflow:core:graph_runs counter
:tensorflow:core:graph_runs{} 10000
# TYPE :tensorflow:data:autotune counter
# TYPE :tensorflow:data:bytes_read counter
# TYPE :tensorflow:data:elements counter
# TYPE :tensorflow:data:optimization counter
# TYPE :tensorflow:serving:model_warmup_latency histogram
# TYPE :tensorflow:serving:request_example_count_total counter
# TYPE :tensorflow:serving:request_example_counts histogram
# TYPE :tensorflow:serving:request_log_count counter
`
but I could only see **:tensorflow:core:graph_runs** counters but there are no counters for  **:tensorflow:serving:request_example_count_total** , **:tensorflow:serving:request_log_count** etc. Am I missing anything here?

**Comment by Arnold1** [comment]
I try to extract TensorFlow Serving metrics. 
how can I see the the number of requests, requests per second, the time tfs needs to serve a request?

```
root@tf-ds-model-1-gbkpm:/# curl localhost:8501/monitoring/prometheus/metrics
# TYPE :tensorflow:cc:saved_model:load_attempt_count counter
:tensorflow:cc:saved_model:load_attempt_count{model_path="s3://ds_model/model1",status="success"} 1
# TYPE :tensorflow:cc:saved_model:load_latency counter
:tensorflow:cc:saved_model:load_latency{model_path="s3://ds_model/model1"} 708801
# TYPE :tensorflow:contrib:session_bundle:load_attempt_count counter
# TYPE :tensorflow:contrib:session_bundle:load_latency counter
# TYPE :tensorflow:core:direct_session_runs counter
:tensorflow:core:direct_session_runs{} 21558641
# TYPE :tensorflow:core:graph_run_time_usecs counter
:tensorflow:core:graph_run_time_usecs{} 168661266983
# TYPE :tensorflow:core:graph_runs counter
:tensorflow:core:graph_runs{} 21558640
# TYPE :tensorflow:serving:model_warmup_latency histogram
# TYPE :tensorflow:serving:request_example_count_total counter
# TYPE :tensorflow:serving:request_example_counts histogram
# TYPE :tensorflow:serving:request_log_count counter
```

**Comment by dannysid** [comment]
A documentation on what represents these metrics and how to use them in production uses cases would be very nice. Right now i'm trying to implement a scaling mechanism for our serving machines and i can just deduct what the metrics are doing.

 Is there such documentation somewhere? because i can't find it

**Comment by Arnold1** [comment]
also is there a way to monitor requests per second into the Tensorflow serving container?

**Comment by pindinagesh** [comment]
@FNegrello 

Could you please respond on the above @litaxc comment .Thanks

**Comment by pindinagesh** [comment]
@FNegrello 

Closing this issue due to inactivity. Please feel free to reopen if this still exist Please feel free to reopen and please try to have a  look at this [documentation.](https://www.tensorflow.org/io/tutorials/prometheus) Some of the above mentioned links are throwing 404 errors. , Thanks

**Comment by windmaple** [comment]
You can see the meaning of the metrics in this file:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/metrics.cc

**Comment by jasonhao518** [comment]
if only things like response time or number of request, use a reverse proxy or istio can solve that without any change in the code. actually more curious about tensorflow specific metrics.
