### ISSUE TITLE
Cannot handle beta versions of bazel

### ISSUE THREAD

**Issue by henrybaxter** [tensorflow/serving#69]
After installing https://github.com/bazelbuild/bazel/releases/download/0.2.2b/bazel-0.2.2b-installer-linux-x86_64.sh the output of `bazel build tensorflow_serving/...` is

```
ERROR: /home/ubuntu/serving/WORKSPACE:18:1: Traceback (most recent call last):
	File "/home/ubuntu/serving/WORKSPACE", line 18
		check_version("0.2.0")
	File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/8bd6e58495e54c8cdf1fb8b1ed15e742/external/tf/tensorflow/tensorflow.bzl", line 22, in check_version
		_parse_bazel_version(native.bazel_version)
	File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/8bd6e58495e54c8cdf1fb8b1ed15e742/external/tf/tensorflow/tensorflow.bzl", line 15, in _parse_bazel_version
		int(number)
invalid literal for int(): "2b".
ERROR: Error evaluating WORKSPACE file.
ERROR: package contains errors: tensorflow_serving.
ERROR: no such package 'external': Package 'external' contains errors.
INFO: Elapsed time: 0.800s
```

Not a big deal, but I guess you can't assume they use numbers in their version strings...

**Comment by kirilg** [comment]
Yes, that was actually already fixed in TensorFlow but at a later commit. We're now synced to an older one because there's something else broken at head... Thanks for bringing this to our attention, I forgot that the "version is a number" assumption is still in place at the commit we're synced to.

**Comment by TobiasWeis** [comment]
Is there a solution to this yet? I just cloned and am running in the same issues..

**Comment by srajendhiran** [comment]
How to fix this Guys? Any updates. Thanks.

**Comment by kirilg** [comment]
Sorry about that. We'll temporarily remove the check and that should be submitted soon. In the meantime, you can work around this by locally removing the one line that checks the version (https://github.com/tensorflow/serving/blob/master/WORKSPACE#L18).

**Comment by chrisolston** [comment]
I've committed a change that removes the version check, so that users won't encounter this problem. (We'll add it back in once it has been updated to handle non-numerical versions properly.)

**Comment by dbl001** [comment]
I'm still getting the errors henry-baxter reported.  Have the changes been pushed to the repository?

**Comment by chrisolston** [comment]
The change that (temporarily) removes the bazel version check was submitted yesterday:
https://github.com/tensorflow/serving/commit/3ec10c7312432ecd6aa4df636e3dc79c2111603c

Can you verify that you have synced to that update? If so, then maybe something in tensorflow is running the check separately from the one in tensorflow_serving that we removed :(

**Comment by dbl001** [comment]
$ git pull
Already up-to-date.

cd tensorflow/
David-Laxers-MacBook-Pro:tensorflow davidlaxer$ ./configure
Please specify the location of python. [Default is /usr/bin/python]: 
Do you wish to build TensorFlow with GPU support? [y/N] N
No GPU support will be enabled for TensorFlow
Configuration finished
David-Laxers-MacBook-Pro:tensorflow davidlaxer$ cd ..
David-Laxers-MacBook-Pro:syntaxnet davidlaxer$ bazel test syntaxnet/... util/utf8/...
.................
ERROR: /Users/davidlaxer/models/syntaxnet/WORKSPACE:11:1: Traceback (most recent call last):
	File "/Users/davidlaxer/models/syntaxnet/WORKSPACE", line 11
		check_version("0.2.0")
	File "/private/var/tmp/_bazel_davidlaxer/568b21ed40364fc3a52b6533eacc811d/external/tf/tensorflow/tensorflow.bzl", line 22, in check_version
		_parse_bazel_version(native.bazel_version)
	File "/private/var/tmp/_bazel_davidlaxer/568b21ed40364fc3a52b6533eacc811d/external/tf/tensorflow/tensorflow.bzl", line 15, in _parse_bazel_version
		int(number)
invalid literal for int(): "2b".
ERROR: Error evaluating WORKSPACE file.
ERROR: package contains errors: syntaxnet.
ERROR: no such package 'external': Package 'external' contains errors.
INFO: Elapsed time: 2.259s
ERROR: Couldn't start the build. Unable to run tests.
David-Laxers-MacBook-Pro:syntaxnet davidlaxer$

**Comment by chrisolston** [comment]
Okay. It seems that tensorflow's check is the one that's failing, and we are triggering it. Unfortunately as Kiril said we cannot move to tensorflow head just yet. We are working on that; hope to get there soon.

In the mean time, as a short-term workaround you could find and comment-out the offending version check in tensorflow.

**Comment by dbl001** [comment]
How do I pull version: 0.2.0?

**Comment by dbl001** [comment]
It’s working with bezel 0.2.3.

**Comment by dbl001** [comment]
//syntaxnet:parser_trainer_test                                          FAILED in 0.0s

…

syntaxnet/parser_trainer_test: line 36: /private/var/tmp/_bazel_davidlaxer/568b21ed40364fc3a52b6533eacc811d/syntaxnet/bazel-out/local-opt/bin/syntaxnet/parser_trainer_test.runfiles/syntaxnet/parser_trainer: No such file or directory

**Comment by kirilg** [comment]
@dbl001 parser_trainer_test is not part of TensorFlow Serving, did you mean to post your last comment in tensorflow/models?
