### ISSUE TITLE
C++ compilation of rule '//tensorflow_serving/util:json_tensor_test' failed

### ISSUE THREAD

**Issue by jin** [tensorflow/serving#905]
Failure from Bazel's latest nightly downstream tests:

```
ERROR: /var/lib/buildkite-agent/builds/buildkite-worker-ubuntu1404-java8-0vv1-1/bazel-downstream-projects/serving/tensorflow_serving/util/BUILD:340:1: Couldn't build file tensorflow_serving/util/_objs/json_tensor_test/tensorflow_serving/util/json_tensor_test.pic.o: C++ compilation of rule '//tensorflow_serving/util:json_tensor_test' failed (Exit 1)
--
  | tensorflow_serving/util/json_tensor_test.cc:60:43: error: unterminated raw string
  | TF_EXPECT_OK(FillPredictRequestFromJson(R"(
  | ^
  | tensorflow_serving/util/json_tensor_test.cc:63:7: warning: missing terminating " character [enabled by default]
  | })",
  | ^
  | tensorflow_serving/util/json_tensor_test.cc:64:64: error: macro "TF_EXPECT_OK" passed 2 arguments, but takes just 1
  | getmap(infomap), &req));
  | ^
  | tensorflow_serving/util/json_tensor_test.cc:67:44: error: unterminated raw string
  | EXPECT_THAT(tmap["default"], EqualsProto(R"(
  | ^
  | tensorflow_serving/util/json_tensor_test.cc:79:6: warning: missing terminating " character [enabled by default]
  | )"));
  | ^
  | tensorflow_serving/util/json_tensor_test.cc:88:43: error: unterminated raw string
  | TF_EXPECT_OK(FillPredictRequestFromJson(R"(

...
```

https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/277#ff9adcb3-426a-4b04-9bfb-ab73f28d7334

cc @chrisolston @netfs

**Comment by nongcunshaoye** [comment]
did you solve this problem ?

**Comment by laszlocsomor** [comment]
I haven't seen this recently. Possibly fixed by https://github.com/bazelbuild/continuous-integration/commit/2b348dc8d4116c679560260920542cc9b5648562

**Comment by laszlocsomor** [comment]
> I haven't seen this recently. Possibly fixed by bazelbuild/continuous-integration@2b348dc

Scratch that, this is still happening on [Bazel CI, Ubuntu 14.04 and 16.04](https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/305):

```
INFO: From Compiling tensorflow_serving/servables/tensorflow/predict_impl.cc:
--
  | tensorflow_serving/servables/tensorflow/predict_impl.cc: In function 'tensorflow::Status tensorflow::serving::{anonymous}::SessionBundlePredict(const tensorflow::RunOptions&, const tensorflow::MetaGraphDef&, const tensorflow::serving::optional<long long int>&, const tensorflow::serving::PredictRequest&, tensorflow::serving::PredictResponse*, tensorflow::Session*)':
  | tensorflow_serving/servables/tensorflow/predict_impl.cc:120:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  | for (int i = 0; i < outputs.size(); i++) {
  | ^
  | ERROR: /var/lib/buildkite-agent/builds/buildkite-worker-ubuntu1404-java8-c53b-1/bazel-downstream-projects/serving/tensorflow_serving/model_servers/BUILD:159:1: Couldn't build file tensorflow_serving/model_servers/_objs/http_rest_prediction_handler_test/http_rest_prediction_handler_test.pic.o: C++ compilation of rule '//tensorflow_serving/model_servers:http_rest_prediction_handler_test' failed (Exit 1)
  | tensorflow_serving/model_servers/http_rest_prediction_handler_test.cc:305:7: error: unterminated raw string
  | R"({
  | ^
  | tensorflow_serving/model_servers/http_rest_prediction_handler_test.cc:307:36: warning: missing terminating " character [enabled by default]
  | "instances": [3.0, 4.0]})",
  | ^
  | tensorflow_serving/model_servers/http_rest_prediction_handler_test.cc:308:24: error: macro "TF_EXPECT_OK" passed 2 arguments, but takes just 1
  | &headers, &output));
  | ^
  | tensorflow_serving/model_servers/http_rest_prediction_handler_test.cc:321:7: error: unterminated raw string
  | R"({
  | ^
  | tensorflow_serving/model_servers/http_rest_prediction_handler_test.cc:324:11: warning: missing terminating " character [enabled by default]
  | })",
  | ^
  | tensorflow_serving/model_servers/http_rest_prediction_handler_test.cc:325:24: error: macro "TF_EXPECT_OK" passed 2 arguments, but takes just 1
  | &headers, &output));
  | ^
  | tensorflow_serving/model_servers/http_rest_prediction_handler_test.cc:335:7: error: unterminated raw string
  | R"({
  | ^
  | tensorflow_serving/model_servers/http_rest_prediction_handler_test.cc:338:11: warning: missing terminating " character [enabled by default]
  | })",
  | ^
  | tensorflow_serving/model_servers/http_rest_prediction_handler_test.cc:339:24: error: macro "TF_EXPECT_OK" passed 2 arguments, but takes just 1
  | &headers, &output));
  | ^
  | tensorflow_serving/model_servers/http_rest_prediction_handler_test.cc:352:7: error: unterminated raw string
  | R"({
  | ^
  | tensorflow_serving/model_servers/http_rest_prediction_handler_test.cc:355:11: warning: missing terminating " character [enabled by default]
  | })",
  | ^
  | tensorflow_serving/model_servers/http_rest_prediction_handler_test.cc:356:24: error: macro "TF_EXPECT_OK" passed 2 arguments, but takes just 1
  | &headers, &output));
  | ^
  | tensorflow_serving/model_servers/http_rest_prediction_handler_test.cc:366:7: error: unterminated raw string
  | R"({
  | ^
  | tensorflow_serving/model_servers/http_rest_prediction_handler_test.cc:369:11: warning: missing terminating " character [enabled by default]
  | })",
  | ^
  | tensorflow_serving/model_servers/http_rest_prediction_handler_test.cc:370:24: error: macro "TF_EXPECT_OK" passed 2 arguments, but takes just 1
  | &headers, &output));
  | ^
  | tensorflow_serving/model_servers/http_rest_prediction_handler_test.cc: In member function 'virtual void tensorflow::serving::{anonymous}::HttpRestPredictionHandlerTest_Predict_Test::TestBody()':
  | tensorflow_serving/model_servers/http_rest_prediction_handler_test.cc:301:3: error: 'TF_EXPECT_OK' was not declared in this scope
  | TF_EXPECT_OK(handler_.ProcessRequest(
  | ^
  | tensorflow_serving/model_servers/http_rest_prediction_handler_test.cc:308:25: error: expected ';' before ')' token
  | &headers, &output));
  | ^
  | tensorflow_serving/model_servers/http_rest_prediction_handler_test.cc: In member function 'virtual void tensorflow::serving::{anonymous}::HttpRestPredictionHandlerTest_Regress_Test::TestBody()':
  | tensorflow_serving/model_servers/http_rest_prediction_handler_test.cc:319:3: error: 'TF_EXPECT_OK' was not declared in this scope
  | TF_EXPECT_OK(handler_.ProcessRequest(
  | ^
  | tensorflow_serving/model_servers/http_rest_prediction_handler_test.cc:325:25: error: expected ';' before ')' token
  | &headers, &output));
  | ^
  | tensorflow_serving/model_servers/http_rest_prediction_handler_test.cc:339:25: error: expected ';' before ')' token
  | &headers, &output));
  | ^
  | tensorflow_serving/model_servers/http_rest_prediction_handler_test.cc: In member function 'virtual void tensorflow::serving::{anonymous}::HttpRestPredictionHandlerTest_Classify_Test::TestBody()':
  | tensorflow_serving/model_servers/http_rest_prediction_handler_test.cc:350:3: error: 'TF_EXPECT_OK' was not declared in this scope
  | TF_EXPECT_OK(handler_.ProcessRequest(
  | ^
  | tensorflow_serving/model_servers/http_rest_prediction_handler_test.cc:356:25: error: expected ';' before ')' token
  | &headers, &output));
  | ^
  | tensorflow_serving/model_servers/http_rest_prediction_handler_test.cc:370:25: error: expected ';' before ')' token
  | &headers, &output));
  | ^
```

**Comment by jin** [comment]
This is now fixed. The Bazel CI tests on 14.04, 16.04 and 18.04. We can remove the 14.04 pipeline for tensorflow_serving if that's the case. cc @buchgr @philwo

**Comment by gautamkmr** [comment]
Hmm I already have the fix, I am using TF-Serving-1.9 but still getting the error with Gcc -4.8.5

**Comment by gautamkmr** [comment]
This is the error 

tensorflow_serving/util/json_tensor_test.cc:60:43: error: unterminated raw string
   TF_EXPECT_OK(FillPredictRequestFromJson(R"(  

I can provide more details if you like

**Comment by gautamkmr** [comment]
https://github.com/tensorflow/serving/issues/1001

**Comment by laszlocsomor** [comment]
@gautamkmr , thanks for the info and the link. #1001 looks like a duplicate of this one. Since that one is newer, mind if I close this one?
